### ISSUE TITLE
Entity crash

### ISSUE THREAD

**Issue by random22** [CraftalotReloaded/Astrolands#2]
Server: 
Incase of a crash, please pastebin the crash report(if present) and the latest.log and include the link(s) to them.
Detailed description:there is an entity i cant look at 

[crash-2018-05-24_05.24.07-client.txt](https://github.com/CraftalotReloaded/Astrolands/files/2035287/crash-2018-05-24_05.24.07-client.txt)

**Comment by CraftalotReloaded** [comment]
Fixed
